import{abi,chains,createClient}from"genlayer-js";import{encodeFunctionData}from"viem";
const CONTRACT="0x8F1CeC7cbf0D651561B5ec11049257e6421efEEc",CHALLENGE_ID="live-contradiction-20260930-a",SPONSOR="0xa35dc047f9937bf668743efbdf8ea93b31a55888",RPC="https://studio-dev.genlayer.com/api",CHAIN_ID=61997,CHAIN_ID_HEX="0xf22d",USER_VALUE=3000000000000n;
const CHAIN={...chains.studionet,id:CHAIN_ID,name:"GenLayer Studio Devnet",rpcUrls:{default:{http:[RPC]},public:{http:[RPC]}}};
const ADD_ABI=[{type:"function",name:"addTransaction",stateMutability:"payable",inputs:[{name:"_params",type:"tuple",components:[
{name:"sender",type:"address"},{name:"recipient",type:"address"},{name:"numOfInitialValidators",type:"uint256"},{name:"maxRotations",type:"uint256"},{name:"validUntil",type:"uint256"},{name:"saltNonce",type:"uint256"},{name:"userValue",type:"uint256"},
{name:"feesDistribution",type:"tuple",components:[{name:"leaderTimeunitsAllocation",type:"uint256"},{name:"validatorTimeunitsAllocation",type:"uint256"},{name:"appealRounds",type:"uint256"},{name:"executionBudgetPerRound",type:"uint256"},{name:"executionConsumed",type:"uint256"},{name:"totalMessageFees",type:"uint256"},{name:"rotations",type:"uint256[]"},{name:"maxPriceGenPerTimeUnit",type:"uint256"},{name:"storageFeeMaxGasPrice",type:"uint256"},{name:"receiptFeeMaxGasPrice",type:"uint256"}]},
{name:"txCalldata",type:"bytes"},{name:"messageAllocations",type:"tuple[]",components:[{name:"messageType",type:"uint8"},{name:"onAcceptance",type:"bool"},{name:"parentIndex",type:"uint256"},{name:"recipient",type:"address"},{name:"callKey",type:"bytes32"},{name:"budget",type:"uint256"},{name:"feeParams",type:"bytes"}]}]}],outputs:[]}];
const $=id=>document.getElementById(id);let provider,client,account;
function stringify(v){const seen=new WeakSet;return JSON.stringify(v,(_,x)=>{if(typeof x==="bigint")return x.toString();if(x instanceof Map)return Object.fromEntries(x);if(x instanceof Uint8Array)return"0x"+Array.from(x,b=>b.toString(16).padStart(2,"0")).join("");if(x&&typeof x==="object"){if(seen.has(x))return"[Circular]";seen.add(x)}return x},2)}
function err(v,seen=new WeakSet,d=0){if(v===null||v===undefined||typeof v!=="object")return v;if(d>6||seen.has(v))return d>6?"[MaxDepth]":"[Circular]";seen.add(v);const o={},keys=new Set(["name","message","code","shortMessage","details","stack","data","cause",...Object.keys(v),...Object.getOwnPropertyNames(v)]);for(const k of keys)try{if(k in v)o[k]=err(v[k],seen,d+1)}catch{o[k]="[Unserializable]"}return o}
function log(label,value){$("log").textContent+=new Date().toISOString()+" "+label+(value===undefined?"":"\n"+stringify(value))+"\n\n";console.log(label,value)}
function status(v,c){$("status").textContent=v;$("status").className=c||""}function hex(v){return"0x"+BigInt(v).toString(16)}function bi(v,n,f=0n){if(v===undefined||v===null||v==="")return f;try{return BigInt(v)}catch{throw new Error(n+" is not an integer")}}function cap(v){return v===0n?0n:(v*12000n+9999n)/10000n}
function providerInfo(v){return v?{isRabby:Boolean(v.isRabby||v._isRabby),isMetaMask:Boolean(v.isMetaMask),hasRequest:typeof v.request==="function"}:null}
function pick(){const injected=window.ethereum,providers=Array.isArray(injected&&injected.providers)?injected.providers.filter(Boolean):(injected?[injected]:[]),selected=providers.find(x=>x.isRabby||x._isRabby)||providers.find(x=>x.isMetaMask)||providers[0];return{injected,providers,selected}}
async function wallet(label,method,params=[]){log("WALLET_REQUEST: "+label,{method,params});try{const result=await provider.request({method,params});log("WALLET_RESPONSE: "+label,{method,result});return result}catch(e){log("WALLET_ERROR: "+label,{method,error:err(e)});throw e}}
function runnerError(message,details){return{name:"AuditRunnerError",code:"AUDIT_RUNNER",message,details}}
function inner(method,args=[]){const obj={"":method};if(args.length)obj.args=args;return abi.transactions.serialize([abi.calldata.encode(obj),false])}
function fromB64(v){const b=Uint8Array.from(atob(v),c=>c.charCodeAt(0));return"0x"+Array.from(b,x=>x.toString(16).padStart(2,"0")).join("")}
function resultHex(v){if(typeof v==="string")return v.startsWith("0x")?v:"0x"+v;if(v&&typeof v==="object"){if(v.status&&v.status.code!==0)throw new Error("gen_call failed: "+(v.status.message||"unknown status"));for(const k of["data","result"])if(typeof v[k]==="string"){if(v[k].startsWith("0x"))return v[k];if(/^[0-9a-fA-F]+$/.test(v[k])&&v[k].length%2===0)return"0x"+v[k];return fromB64(v[k])}}throw new Error("Unexpected GenLayer response: "+stringify(v))}
function bytes(v){v=v.startsWith("0x")?v.slice(2):v;const out=new Uint8Array(v.length/2);for(let i=0;i<out.length;i++)out[i]=parseInt(v.slice(i*2,i*2+2),16);return out}
function plain(v){if(v instanceof Map)return Object.fromEntries([...v].map(([k,x])=>[k,plain(x)]));if(Array.isArray(v))return v.map(plain);if(v instanceof Uint8Array)return"0x"+Array.from(v,b=>b.toString(16).padStart(2,"0")).join("");return v}
async function readChallenge(label){const r=await client.request({method:"gen_call",params:[{type:"read",to:CONTRACT,from:account,data:inner("get_challenge",[CHALLENGE_ID]),transaction_hash_variant:"latest-nonfinal"}]});const challenge=plain(abi.calldata.decode(bytes(resultHex(r))));$("challenge").textContent=stringify({label,challenge});log("AUTHORITATIVE_CHALLENGE_READ",{label,challenge});return challenge}
function preset(v,d=0){if(!v||typeof v!=="object"||d>8)return null;if(v.recommendedPreset&&v.recommendedPreset.distribution&&v.recommendedPreset.feeValue!==undefined)return v.recommendedPreset;for(const x of Object.values(v)){const p=preset(x,d+1);if(p)return p}return null}
function rpcDist(d){return{leaderTimeunitsAllocation:d.leaderTimeunitsAllocation.toString(),validatorTimeunitsAllocation:d.validatorTimeunitsAllocation.toString(),appealRounds:d.appealRounds.toString(),executionBudgetPerRound:d.executionBudgetPerRound.toString(),executionConsumed:d.executionConsumed.toString(),totalMessageFees:d.totalMessageFees.toString(),rotations:d.rotations.map(x=>x.toString()),maxPriceGenPerTimeUnit:d.maxPriceGenPerTimeUnit.toString(),storageFeeMaxGasPrice:d.storageFeeMaxGasPrice.toString(),receiptFeeMaxGasPrice:d.receiptFeeMaxGasPrice.toString()}}
function presetDist(x){return{leaderTimeunitsAllocation:bi(x.leaderTimeunitsAllocation,"leader"),validatorTimeunitsAllocation:bi(x.validatorTimeunitsAllocation,"validator"),appealRounds:bi(x.appealRounds,"appeal"),executionBudgetPerRound:bi(x.executionBudgetPerRound,"execution"),executionConsumed:bi(x.executionConsumed,"consumed"),totalMessageFees:bi(x.totalMessageFees,"message fees"),rotations:(x.rotations||[]).map(y=>bi(y,"rotation")),maxPriceGenPerTimeUnit:bi(x.maxPriceGenPerTimeUnit,"time price"),storageFeeMaxGasPrice:bi(x.storageFeeMaxGasPrice,"storage price"),receiptFeeMaxGasPrice:bi(x.receiptFeeMaxGasPrice,"receipt price")}}
function localFee(d,p){const n=bi(client.chain.defaultNumberOfInitialValidators,"validators"),overlay=bi(p.timeUnitOverlayBps,"overlay"),work=(d.rotations[0]+1n)*(100n+n*200n)*d.maxPriceGenPerTimeUnit,over=overlay===0n?0n:work*overlay/(10000n-overlay),rounds=d.rotations.reduce((s,x)=>s+x+1n,d.appealRounds);return work+over+d.executionBudgetPerRound*rounds+d.totalMessageFees}
async function estimate(){const p=(await client.request({method:"sim_getFeeConfig",params:[]})).policy;if(!p)throw new Error("Studio did not return a fee policy");const floor=bi(p.messageFeeParamsBudgetFloor,"budget floor"),receipt=bi(p.receiptGasPrice,"receipt price"),d={leaderTimeunitsAllocation:100n,validatorTimeunitsAllocation:200n,appealRounds:0n,executionBudgetPerRound:[500000n,floor,receipt*100000000n].reduce((a,b)=>a>b?a:b),executionConsumed:0n,totalMessageFees:0n,rotations:[bi(client.chain.defaultConsensusMaxRotations,"max rotations")],maxPriceGenPerTimeUnit:cap(bi(p.genPerTimeUnit,"time price")),storageFeeMaxGasPrice:cap(bi(p.storageUnitPrice,"storage price")),receiptFeeMaxGasPrice:cap(receipt)};let r;try{r=await client.request({method:"sim_estimateTransactionFees",params:[{type:"write",to:CONTRACT,from:account,data:inner("fund_challenge",[CHALLENGE_ID]),value:hex(USER_VALUE),fees:{distribution:rpcDist(d),messageAllocations:[],feeValue:localFee(d,p).toString()},transaction_hash_variant:"latest-nonfinal"}]})}catch(e){r=err(e);log("FEE_ESTIMATE_RPC_ERROR",r)}const q=preset(r);if(!q)throw new Error("No recommended fee preset: "+stringify(r));const out={policy:p,distribution:presetDist(q.distribution),feeValue:bi(q.feeValue,"fee value")};log("FEE_ESTIMATE",{api:"sim_getFeeConfig + sim_estimateTransactionFees; verified against installed CLI 0.40.0-rc.3",policy:p,distribution:out.distribution,feeValue:out.feeValue});return out}
function outer(estimate){const params={sender:account,recipient:CONTRACT,numOfInitialValidators:bi(client.chain.defaultNumberOfInitialValidators,"validators"),maxRotations:bi(client.chain.defaultConsensusMaxRotations,"max rotations"),validUntil:BigInt(Math.floor(Date.now()/1000)+3600),saltNonce:0n,userValue:USER_VALUE,feesDistribution:estimate.distribution,txCalldata:inner("fund_challenge",[CHALLENGE_ID]),messageAllocations:[]};return encodeFunctionData({abi:ADD_ABI,functionName:"addTransaction",args:[params]})}
async function prepare(estimate){const destination=client.chain.consensusMainContract&&client.chain.consensusMainContract.address;if(!destination)throw new Error("No consensus main address in installed SDK chain config");const total=USER_VALUE+estimate.feeValue,base={from:account,to:destination,data:outer(estimate),value:hex(total),chainId:CHAIN_ID_HEX,type:"0x0"},gas=await wallet("eth_estimateGas","eth_estimateGas",[base]),nonce=await wallet("eth_getTransactionCount","eth_getTransactionCount",[account,"pending"]);let gasPrice;try{gasPrice=await wallet("eth_gasPrice","eth_gasPrice")}catch(e){log("GAS_PRICE_UNAVAILABLE",err(e))}const tx={...base,gas,nonce};if(gasPrice!==undefined)tx.gasPrice=gasPrice;log("PRE_SIGN_TRANSACTION",{contract:CONTRACT,method:"fund_challenge",args:[CHALLENGE_ID],encodedGenLayerRecipient:CONTRACT,transactionDestination:destination,userValue:USER_VALUE,feeValue:estimate.feeValue,totalEnvelope:total,completeFeeDistribution:estimate.distribution,gasEstimate:gas,connectedAccount:account,chain:CHAIN_ID,transaction:tx});return tx}
async function connect(){const s=pick();log("INJECTED_PROVIDER_SELECTION",{providerVisible:Boolean(s.injected),providerCount:s.providers.length,candidates:s.providers.map(providerInfo),selected:providerInfo(s.selected)});if(!s.selected||typeof s.selected.request!=="function")throw runnerError("No EIP-1193 wallet provider found",s);provider=s.selected;const requested=await wallet("eth_requestAccounts","eth_requestAccounts"),before=await wallet("eth_chainId","eth_chainId");if(String(before).toLowerCase()!==CHAIN_ID_HEX){try{await wallet("wallet_switchEthereumChain","wallet_switchEthereumChain",[{chainId:CHAIN_ID_HEX}])}catch(e){const x=err(e),code=x&&(x.code||(x.data&&x.data.originalError&&x.data.originalError.code));if(code!==4902&&code!=="4902")throw e;await wallet("wallet_addEthereumChain","wallet_addEthereumChain",[{chainId:CHAIN_ID_HEX,chainName:CHAIN.name,nativeCurrency:{name:"GEN",symbol:"GEN",decimals:18},rpcUrls:[RPC]}]);await wallet("wallet_switchEthereumChain after add","wallet_switchEthereumChain",[{chainId:CHAIN_ID_HEX}])}}const chain=await wallet("eth_chainId after switch","eth_chainId");if(String(chain).toLowerCase()!==CHAIN_ID_HEX)throw runnerError("Wallet did not switch to Studio Dev",{expected:CHAIN_ID_HEX,actual:chain});account=(await wallet("eth_accounts","eth_accounts"))?.[0]||requested?.[0];if(!account||account.toLowerCase()!==SPONSOR.toLowerCase())throw runnerError("Connected wallet is not the required sponsor",{connected:account,required:SPONSOR});client=createClient({chain:CHAIN,endpoint:RPC,account,provider});$("wallet").textContent=account;$("chain").textContent=CHAIN_ID+" ("+CHAIN_ID_HEX+")";const c=await readChallenge("before funding"),state=String(c.state??c.status??""),funded=bi(c.escrow_funded,"escrow_funded"),expected=bi(c.expected_escrow,"expected escrow");if(state!=="DRAFT"||funded!==0n||expected!==USER_VALUE)throw runnerError("Challenge is not the expected unfunded DRAFT",{state,funded,expected,expectedUserValue:USER_VALUE});$("fund").disabled=false;status("ready for one manual funding click","ok");log("RUNNER_READY",{sponsor:account,chain:CHAIN_ID,challenge:CHALLENGE_ID,expectedEscrow:expected})}
async function fund(){ $("fund").disabled=true;status("refreshing read and preparing fee-aware transaction...","warning");const c=await readChallenge("immediately before funding");if(String(c.state??c.status??"")!=="DRAFT"||bi(c.escrow_funded,"escrow funded")!==0n)throw runnerError("Challenge changed before signing; refusing to send",{challenge:c});const estimateResult=await estimate(),tx=await prepare(estimateResult);log("WALLET_SIGNING_NEXT",{note:"No transaction is submitted until the sponsor approves the wallet prompt"});const hash=await wallet("eth_sendTransaction","eth_sendTransaction",[tx]);log("GENLAYER_TRANSACTION_SUBMITTED",{transactionId:hash});status("submitted; waiting for ACCEPTED then FINALIZED...","warning");const accepted=await client.waitForTransactionReceipt({hash,status:"ACCEPTED",interval:1000,retries:180,fullTransaction:true});log("GENLAYER_ACCEPTED",accepted);const finalized=await client.waitForTransactionReceipt({hash,status:"FINALIZED",interval:1000,retries:600,fullTransaction:true}),details=await client.getTransaction({hash});log("GENLAYER_FINALIZED",{finalized,details});if(details.txExecutionResultName&&details.txExecutionResultName!=="FINISHED_WITH_RETURN")throw new Error("GenLayer execution did not succeed: "+details.txExecutionResultName);await readChallenge("after finalization");status("funding finalized and challenge reread","ok")}
$("fund").addEventListener("click",()=>fund().catch(e=>{log("ACTION_ERROR: fund live challenge",err(e));status("funding failed; see structured log","bad");$("fund").disabled=false}));
connect().catch(e=>{log("ACTION_ERROR: connect and prepare",err(e));status("not ready; see structured log","bad")});
